name: Mid-Cap Portfolio Daily Update

on:
  schedule:
    # Run at 8:20 PM UTC (4:20 PM EST, after market close)
    - cron: '20 20 * * 1-5'
  workflow_dispatch:  # Allow manual runs

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run portfolio update
      env:
        ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
      run: |
        python main.py
    
    - name: Generate stop loss report
      env:
        ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
      run: |
        python trailing_stops_report.py
    
    - name: Generate daily report
      run: |
        cd reporting
        python portfolio_report_generator.py
    
    - name: Update dashboard
      run: |
        python update_dashboard.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "📈 Daily portfolio update $(date +'%Y-%m-%d')"
        git push

  stop-loss-monitor:
    runs-on: ubuntu-latest
    needs: update-portfolio
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check for stop loss alerts
      env:
        ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
      run: |
        python check_stops.py
    
    - name: Send alerts if triggered
      if: hashFiles('data/stop_alerts.json') != ''
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python send_alerts.py

  benchmark-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas
    
    - name: Update benchmark data
      run: |
        python update_benchmarks.py
    
    - name: Commit benchmark updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/benchmark_*.csv
        git diff --staged --quiet || git commit -m "📊 Benchmark data update $(date +'%Y-%m-%d')"
        git push
