name: Mid-Cap Portfolio Daily Update
on:
  schedule:
    # Run at 8:20 PM UTC (4:20 PM EST, after market close)
    - cron: '20 20 * * 1-5'
  workflow_dispatch:  # Allow manual runs

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run portfolio update
      env:
        ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        ALPACA_API_KEY_ID: ${{ secrets.ALPACA_API_KEY_ID }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        ALPACA_BASE_URL: ${{ secrets.ALPACA_BASE_URL }}
      run: |
        python main.py
    
    - name: Pull latest changes and commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin main --rebase --autostash
        git add .
        git diff --staged --quiet || git commit -m "📈 Daily portfolio update $(date +'%Y-%m-%d')"
        git push origin main

  benchmark-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas
    
    - name: Update benchmark data
      run: |
        python update_benchmarks.py
    
    - name: Pull latest and commit benchmark updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin main --rebase --autostash
        git add data/benchmark_*.csv
        git diff --staged --quiet || git commit -m "📊 Benchmark data update $(date +'%Y-%m-%d')"
        git push origin main
